### PR TITLE
Add tool options for size and shape

### LINKED ISSUE #35: Allow different pencil cursor sizes
I haven't really looked into this yet, but it would be really convenient to allow different pencil sizes for larger artwork. 

Currently, only the single pixel the cursor is on is drawn. I believe we could track pencil size and allow larger draw areas which expand around the currently hovered pixel. 

Just as a note: currently the "preview" of the pixel to be drawn is just an additional hidden layer.

### PR DESCRIPTION
**Pull request by no1hitjam**
Hotkeys included

resolves #35

### CODE REVIEW

**Comment by foxnne** [comment]
Thank you so much! I will take a look at this as soon as I have time. One note I'm a bit unsure of, I've been working on the `sysgpu` branch (and I also apologize this wasn't obvious), but allowing this project to use `sysgpu` required moving to a different binding so the other branch is a pretty hefty change to most of the project. I haven't really ever had much outside contribution so I'm a bit unfamiliar with the best way to handle merging these PR's.

**Comment by no1hitjam** [comment]
Got it, no problem. I'm not too experienced with git merges, but if it's a drastic difference I could imagine just reworking the change off of the new branch, which hopefully isn't too painful. It's something I could possibly look into once that stuff gets figured out.

**Comment by foxnne** [comment]
No worries! Worst case I can just work off your PR like you said. Thanks again!

**Comment by foxnne** [comment]
@no1hitjam Thanks again so much for your PR. I worked off of it and I'm about to merge those changes. I did things a little differently but overall all the same functionality is there. Bracket keys increase/decrease the stroke size. You can right click the pencil tool for a context menu with the options for it there, and a help text has been added to the hover popup over pencil/eraser.

**Pull request closed without merging**
